# Generated by Django 5.2.1 on 2025-06-13 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreport',
            options={'ordering': ['-date'], 'verbose_name': 'Satış Raporu', 'verbose_name_plural': 'Satış Raporları'},
        ),
        migrations.AddField(
            model_name='salesreport',
            name='average_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
