# Generated by Django 5.2.1 on 2025-06-13 08:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_salesreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
